import fs from "node:fs";
import { createPublicClient, createWalletClient, http, parseEther } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { baseSepolia } from "viem/chains";
const key = process.env.DEPLOYER_PRIVATE_KEY;
if (!key) throw new Error("Set DEPLOYER_PRIVATE_KEY for a funded Base Sepolia wallet");
const account = privateKeyToAccount(key);
const rpc = process.env.BASE_SEPOLIA_RPC_URL || "https://sepolia.base.org";
const wallet = createWalletClient({ account, chain: baseSepolia, transport: http(rpc) });
const publicClient = createPublicClient({ chain: baseSepolia, transport: http(rpc) });
const read = (name) => JSON.parse(fs.readFileSync(`artifacts/${name}.json`, "utf8"));
const tokenArtifact = read("MockB20"); const registryArtifact = read("EquityKey");
const tokenHash = await wallet.deployContract({ abi: tokenArtifact.abi, bytecode: tokenArtifact.bytecode });
const token = (await publicClient.waitForTransactionReceipt({ hash: tokenHash })).contractAddress;
const registryHash = await wallet.deployContract({ abi: registryArtifact.abi, bytecode: registryArtifact.bytecode });
const registry = (await publicClient.waitForTransactionReceipt({ hash: registryHash })).contractAddress;
await publicClient.waitForTransactionReceipt({ hash: await wallet.writeContract({ address: registry, abi: registryArtifact.abi, functionName: "setAcceptedToken", args: [token, true] }) });
await publicClient.waitForTransactionReceipt({ hash: await wallet.writeContract({ address: registry, abi: registryArtifact.abi, functionName: "createBenefit", args: [0, [token], [parseEther("0.25")], 0n, true, "ipfs://equitykey-demo-benefit-v1"] }) });
console.log(JSON.stringify({ NEXT_PUBLIC_DEMO_TOKEN_ADDRESS: token, NEXT_PUBLIC_EQUITYKEY_ADDRESS: registry }, null, 2));
